swagger: "2.0"
info:
  version: "0.0.1"
  title: Business Model Canvas API
host: localhost:10510
basePath: /v1
# 
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
produces:
  - application/json
paths:
  /businessModelCanvas:
    x-swagger-router-controller: businessModelCanvas
    get:
      security:
        - Bearer: [] 
      description: Returns an array of canvases
      operationId: canvasFind
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/BusinessModelCanvas"
        "403":
          description: "Access Denied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  BusinessModelCanvas:
    properties:
      id:
        type: string
      name:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
