swagger: "2.0"
info:
  version: "0.0.1"
  title: Business Model Canvas API
host: localhost:80
basePath: /v1
#
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
produces:
  - application/json
paths:
  /businessModelCanvas:
    x-swagger-router-controller: businessModelCanvas
    post:
      security:
        - Bearer: []
      tags:
        - BusinessModelCanvas
      operationId: canvasCreate
      summary: canvasCreate
      description: ''
      deprecated: false
      parameters:
        - name: canvas
          in: body
          required: true
          schema:
            $ref: '#/definitions/BusinessModelCanvas'
      responses:
        '201':
          description: BusinessModelCanvas
          schema:
            $ref: '#/definitions/BusinessModelCanvas'
    get:
      security:
        - Bearer: []
      description: Returns an array of canvases
      operationId: canvasFind
      parameters:
        - name: fields
          in: query
          required: false
          description: ''
          type: string
        - name: page
          in: query
          required: false
          description: ''
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/BusinessModelCanvas"
        "403":
          description: "Access Denied"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /businessModelCanvas/{id}:
    x-swagger-router-controller: businessModelCanvas
    get:
      security:
        - Bearer: []
      description: Returns one business model canvas
      operationId: canvasGet
      parameters:
        - name: id
          in: path
          required: true
          description: ''
          type: string
        - name: fields
          in: query
          required: false
          description: ''
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/BusinessModelCanvas"
        "403":
          description: "Access Denied"
          schema:
            $ref: "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  BusinessModelCanvas:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      status:
        type: string
      owner:
        type: string
      created:
        type: string
      modified:
        type: number
      private:
        type: number
      keyPartner:
        type: array
        items:
          $ref: "#/definitions/KeyPartner"
      keyAcitivity:
        type: array
        items:
          $ref: "#/definitions/KeyActivity"
      keyResource:
        type: array
        items:
          $ref: "#/definitions/KeyResource"
      valueProposition:
        type: array
        items:
          $ref: "#/definitions/ValueProposition"
      customerRelationship:
        type: array
        items:
          $ref: "#/definitions/CustomerRelationship"
      customerSegment:
        type: array
        items:
          $ref: "#/definitions/CustomerSegment"
      channel:
        type: array
        items:
          $ref: "#/definitions/Channel"
      costStructure:
        type: array
        items:
          $ref: "#/definitions/CostStructure"
      revenueStream:
        type: array
        items:
          $ref: "#/definitions/RevenueStream"
  KeyPartner:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  KeyActivity:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  KeyResource:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  ValueProposition:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  CustomerRelationship:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  Channel:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  CustomerSegment:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  CostStructure:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  RevenueStream:
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: array
        items:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
